<form class="form-horizontal" role="form" id="<?php echo $this->formId ?>">
<?php foreach($this->fields as $name => $field): ?>
        <div class="form-group">
            <div class="col-md-3">
                <label title="<?php echo $field['type'] ?>"><?php echo $field['name'] ?></label>
            </div>
            <div class="col-md-2">
<?php if($field['functions']['type'] === 'name'): ?>
                <label class=""><?php echo $field['functions']['name'] ?></label>
<?php elseif($field['functions']['type'] === 'select'): ?>
                <select name="<?php echo $field['functions']['name'] ?>" class="form-control">
<?php foreach($field['functions']['options'] as $function): ?>
                    <option <?php if($function === $field['functions']['selected']): ?>selected<?php
                        endif ?>><?php echo $function ?></option>
<?php endforeach ?>
                </select>
<?php endif ?>
            </div>
            <div class="col-md-7">
<?php if($field['input']['type'] === 'radio' || $field['input']['type'] === 'checkbox'): ?>
                <div class="<?php echo $field['input']['type'] ?>">
<?php foreach($field['input']['value'] as $value): ?>
                    <?php echo $value ?>
<?php endforeach ?>
                </div>
<?php else: ?>
<?php /* Since this HTML code is generated by the Adminer code, we need to add our class name here.*/ ?>
                <?php echo str_replace('name=', 'class="form-control" name=', $field['input']['value']) ?>
<?php endif ?>
            </div>
        </div>
<?php endforeach ?>
    </form>
